### ISSUE TITLE
Color consistency

### ISSUE THREAD

**Issue by sorin-davidoi** [tynn/close-tab-button#1]
On the latest Firefox Nightly, the close button has a slightly different color than the other buttons. ![screenshot_20171026-150756](https://user-images.githubusercontent.com/2109702/32054750-c9366bdc-ba5f-11e7-83a3-fe60d0447297.png)

**Comment by tynn** [comment]
If it's the only one, I find it nicer, but like this it doesn't look right. Thank you for your input. I'll see to find another better fitting icon.

**Comment by sorin-davidoi** [comment]
I guess two icons are needed? This is how it look in a private tab: ![screenshot_20171029-182505](https://user-images.githubusercontent.com/2109702/32146381-dcf9dab8-bcd6-11e7-90e2-8e0bde41f977.png)

**Comment by Keith94** [comment]
Any news?
